# Generated by Django 4.2.4 on 2024-01-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramMixin",
            fields=[
                (
                    "tg_id",
                    models.BigIntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Телеграм ID",
                    ),
                ),
            ],
        ),
    ]
