# Generated by Django 4.2.4 on 2024-01-11 14:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0002_student_api_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="api_token",
            field=models.UUIDField(
                default=uuid.uuid4, unique=True, verbose_name="API Токен"
            ),
        ),
    ]
