# Generated by Django 4.2.4 on 2024-01-11 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="VK ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="Район",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Регион"
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="VK ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="locations.city",
                        verbose_name="Город",
                    ),
                ),
            ],
            options={
                "verbose_name": "Школа",
                "verbose_name_plural": "Школы",
            },
        ),
    ]
